services:
  alpine-miniforge-jupyter-app:
    build:
      context: .
    command:
      - bash
      - run_jupyter
    platform: linux/arm64/v8
    container_name: alpine-miniforge-jupyter-arm64-container
    environment:
      - PASSWORD=123456
      #- http_proxy=http://IP:PORT
      #- https_proxy=http://IP:PORT
      #- all_proxy=socks5://IP:PORT
    image: ghcr.io/uilgnod-liamtoh/alpine-miniforge-jupyter:latest
    #network_mode: bridge
    networks:
        - app-net
    ports:
      - "8888:8888"
    privileged: true
    restart: "always"
    logging:
      driver: json-file
      options:
        max-size: 1m
    volumes:
      - ./jupyter/notebook/:/notebook
      - ./jupyter/.jupyter/:/root/.jupyter/

networks:
  app-net:
    driver: bridge
    external: true
